### ISSUE TITLE
The link to out.yuv file of YUV2RGBSample is broken

### ISSUE THREAD

**Issue by siliangZ** [Xilinx/SDKOpenGLES#9]
https://drive.google.com/open?id=1x-iDJurB3rB9TrF_Wa-4uARr8YtTxfzc
is a broken link and without the out.yuv YUV2RGBSample can not run.
Is there another way to download the test file?

**Comment by alokguptaxilinx** [comment]
you can use any YUV format file.
Ref - https://engineering.purdue.edu/~reibman/ece634/Videos/YUV_videos/

**Comment by siliangZ** [comment]
Cool, thanks for sharing.
